name: repo-init
description: Prepares the repository
inputs:
  token:
    description: NPM token
    required: true

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: "https://registry.npmjs.org"

    - name: Setup .npmrc
      shell: bash
      run: |
        npm set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Ensure access
      shell: bash
      run: npm whoami --registry https://registry.npmjs.org/
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Config git user
      shell: bash
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Install dependencies
      shell: bash
      run: yarn
